name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUSINESSNZ_API_KEY:  ${{ secrets.BUSINESSNZ_API_KEY }}
      BUSINESSNZ_API_SECRET:  ${{ secrets.BUSINESSNZ_API_SECRET }}

    steps:
      # Checkout repo
      - uses: actions/checkout@v2

      # Install go
      - uses: actions/setup-go@v2

      # Run tests
      - name: "Run tests"
        run: |
          go test ./...
